### ISSUE TITLE
ignite package error duing eval "ModuleNotFoundError: No module named 'ignite.exceptions'"

### ISSUE THREAD

**Issue by AvidahRai** [zihuixue/DynMM#1]
Thank you for your work.

```
Traceback (most recent call last):
  File "/content/DynMM/FusionDynMM/eval.py", line 16, in <module>
    from src.confusion_matrix import ConfusionMatrixTensorflow, ConfusionMatrixPytorch, miou_pytorch
  File "/content/DynMM/FusionDynMM/src/confusion_matrix.py", line 13, in <module>
    from ignite.exceptions import NotComputableError
ModuleNotFoundError: No module named 'ignite.exceptions'
```
Trying to run this in Google Colab. ESANet's rgbd_segmentation.yaml requires ignite=0.2.1=py37_0 whereas pip only has versions 1.0.0 and 1.1.0.

I was doing benchmark evaluations for dissertation. Fix would be appreciated.

**Comment by zihuixue** [comment]
Hi @AvidahRai, thanks for the question! It is suggested that you refer to the original [ESANet repo](https://github.com/TUI-NICR/ESANet) for setting up the environment.
