### ISSUE TITLE
"Copy folders from ModalityDynMM to MultiBench"

### ISSUE THREAD

**Issue by 1247388421** [zihuixue/DynMM#2]
您好，我想问下 如果我想进行Modality-level DynMM， 是将 ModalityDynMM文件夹下的 affect  multimedia 与 MultiBench/examples 下对应的同名文件夹进行替换，并将ModalityDynMM/training_structures/Supervised_Learning.py  与 MultiBench里对应的同名文件进行替换。是这样吗？ 期待您的回复，感谢！

**Comment by zihuixue** [comment]
嗯谢谢提问，是这样的。有后续问题欢迎随时提问
